apiVersion: appdirector.randoli.ca/v1beta1
kind: AppInsightsAgent
metadata:
  name: app-insights-agent
spec:
  namespace: app-director
  agentCertsSecretName: appdir-agent-certs
  agentConfigSecretName: appdir-agent-secret
  prometheusUrl: http://prometheus-operated.prometheus.svc.cluster.local:9090
  openCostURL: http://opencost.opencost.svc.cluster.local:9003
